# Generated by Django 4.0.1 on 2022-01-27 20:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('published', 'published'), ('reviewed', 'reviewed')], default='published', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(help_text='Some help text that is shown in documentation', max_length=300, verbose_name='example name')),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status', verbose_name='publishing datetime', when={'published'})),
            ],
            options={
                'db_table': 'examples',
            },
        ),
    ]
