# Generated by Django 3.1.4 on 2020-12-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='is_published',
            field=models.BooleanField(db_index=True, verbose_name='is published?'),
        ),
        migrations.AlterField(
            model_name='example',
            name='name',
            field=models.CharField(help_text='Some help text that is shown in documentation', max_length=300, verbose_name='example name'),
        ),
    ]
