# Generated by Django 3.1.4 on 2020-12-25 13:33

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201225_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='example image'),
        ),
    ]
