# Generated by Django 3.1.4 on 2021-01-05 19:46

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201225_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='image',
        ),
        migrations.AlterField(
            model_name='example',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status', verbose_name='publishing datetime', when={'published'}),
        ),
    ]
